### ISSUE TITLE
BP-3216 CSS modal class overides PrestaShop CSS settings

### ISSUE THREAD

**Issue by gadnis** [buckaroo-it/PrestaShop#102]
Your css code overrides .modal class as you can see [here](https://github.com/buckaroo-it/PrestaShop/blob/71e31fce3066d1e990c3d2047b3d3da15818bd83/views/css/buckaroo3.css#L5).  And this brakes prestashop product quick view modal appearance with warehouse theme installed.

I believe you should be more specific when using global known css class name for your module, it definitelly cannot change existing css settings. Probably all your modalls should be wrapped with `buckaroo` css class, for example:
`
.buckaroo.modal { ... }
`

**Comment by Buckaroo-Rene** [comment]
@gadnis Thank you for your message. We'll look into this.

**Comment by Buckaroo-Rene** [comment]
@gadnis ,
Thanks again, this issue is resolved in our latest release:
https://github.com/buckaroo-it/PrestaShop/releases/tag/4.1.0

Happy Holidays
