### ISSUE TITLE
BP-3241 Refunds is not possible in LIVE

### ISSUE THREAD

**Issue by gadnis** [buckaroo-it/PrestaShop#105]
There is an error when trying to refund from admin orders page. 

The message "Test refunds are not allowed on live transactions" is being shown after click "refund" button.
[Error pic](https://prnt.sc/MvkichBcvZou)

In module settings page the option "Yes, I'm ready to receive payments" is active.
[Settings picture](https://prnt.sc/569BnQKxPzXi)

In configuration table I see that `BUCKAROO_TEST` is set to `1`
[Configuration table picture](https://prnt.sc/ULutMrn1KCdA)

But in the file modules/buckaroo3/classes/Config.php:28 it's written that `live` is when `BUCKAROO_TEST` is `0` which is not, which must be `1`.
[code picture](https://prnt.sc/bFjQsyGn7S9J)

Module version 4.0.1

**Comment by Buckaroo-Rene** [comment]
Hi @gadnis,

Thank you for contacting us.
We'll look into this issue.

**Comment by Buckaroo-Rene** [comment]
@gadnis,
This is already fixed on our development branch.
We are currently preparing a new 4.1.0 release which our QA's will start testing and when that is done we'll release it.
However this will take approximately one more week.

**Comment by gadnis** [comment]
@Buckaroo-Rene,
I already fixed that on my page, good to know you know about it. 
Best wishes

**Comment by Buckaroo-Rene** [comment]
@gadnis ,
Thanks again for informing us about the issue.
I know that you managed to fix it on your side already, but we did a new release today that contains the fix as well together with some other fixes, improvements and new features.

https://github.com/buckaroo-it/PrestaShop/releases/tag/4.1.0

Happy Holidays

**Comment by gadnis** [comment]
Thank you very much, @Buckaroo-Rene

Happy Holidays to you too
