### ISSUE TITLE
Compatibility Issue with Prestashop v1.7.x

### ISSUE THREAD

**Issue by krista11** [buckaroo-it/PrestaShop#107]
There is an error when trying to test connection on BO, also it shows up on order page
![image](https://github.com/buckaroo-it/PrestaShop/assets/36960624/d1c2f16a-2855-4c07-9370-55cafa0c63be)

It seems that Guzzlehttp Client was loaded from PS vendor folder, not module..

Also facing issue on order validation

![MicrosoftTeams-image (5)](https://github.com/buckaroo-it/PrestaShop/assets/36960624/7408ae04-883e-49f7-94f0-76b292798ef6)

PrestaShop version: 1.7.8.9 
PHP version: 7.4.33 
Module version: 4.0.1

**Comment by Buckaroo-Rene** [comment]
@krista11 ,

Thank you for contacting us about the issue that you are facing.
We will look into it.

**Comment by Buckaroo-Rene** [comment]
@krista11 ,
A fix for this issue will be included in our next release that we are currently preparing.
It still needs some days to test the whole release, but we keep you posted about the process.

**Comment by Buckaroo-Rene** [comment]
@krista11 ,

Sorry, but preparing the new release took a bit longer than expected unfortunately.
We managed to released it today and this should resolve your isse.
[https://github.com/buckaroo-it/PrestaShop/releases/tag/4.1.0](https://github.com/buckaroo-it/PrestaShop/releases/tag/4.1.0)
