### ISSUE TITLE
BP-3313 Issuer label image invisible on the checkout

### ISSUE THREAD

**Issue by gadnis** [buckaroo-it/PrestaShop#119]
There's no issuer images in the checkout page, because svg image padding is wrong.

[No image screenshot](https://prnt.sc/wNTrHjaz8rH-)
[fix screenshot](https://prnt.sc/RVb038KE9TSv)

Module version 4.1.0

**Comment by Buckaroo-Rene** [comment]
@gadnis ,
Thanks for informing us about this issue. We will look into it right now.
I expect that we will do a hotfix release for this.
Will let you know when there is more information.

**Comment by Buckaroo-Rene** [comment]
@gadnis,
We do not see this issue on our stagings for PrestaShop 1.7.x and 1.8.x.
Can you perhaps share more information of the template that you are using or perhaps share your website URL with us so we can take a look at your checkout?

Looking forward to your reply.

**Comment by gadnis** [comment]
@Buckaroo-Rene,
We are using [Warehouse theme](https://themeforest.net/item/warehouse-responsive-prestashop-16-theme-blog/3178575?gad_source=1&gclid=CjwKCAiAhJWsBhAaEiwAmrNyq8HarL948ALexH_dZ8gVq5SlOq57zACuRvFNuKLYgp8JwSzmVX7bNxoC9FgQAvD_BwE)
[Our webpage link](https://www.adeachocolate.com/). We decided to show issuers in `Dropdown`, but I will turn `Radio` for now.  

At our side I already fixed problem by changing css `padding: 10px 0;` in [buckaroo3.css:481](https://github.com/buckaroo-it/PrestaShop/blob/71e31fce3066d1e990c3d2047b3d3da15818bd83/views/css/buckaroo3.css#L481)

**Comment by vegimcarkaxhija** [comment]
Hi @gadnis,
Did you try to clear cache which is under Performance in Advanced Parameters, the reason I`m saying this is that I`m seeing some old classes in css that we are not using anymore in new relase, so that should be the problem that you`re facing with issuers.

**Comment by gadnis** [comment]
Hi @vegimcarkaxhija,
My bad.. I had those classes in my custom css. 
Those icons wasn't good looking in previous version 😁 Now it's good. 
Thank you and sorry next time I will investigate more before opening an issue.

**Comment by Buckaroo-Rene** [comment]
@gadnis,
Thank you for your quick reply and no problem.

Happy Holidays!
