### ISSUE TITLE
BP-3431 Prevent transaction requests without selecting an issuer

### ISSUE THREAD

**Issue by gadnis** [buckaroo-it/PrestaShop#128]
It seems that something is duplicating orders untill we have successfully confirmed payment by buckaroo.

As you can see in the [screenshot](https://prnt.sc/X7D8gv3vwwFe) there's is small amount of time between each of these orders. There's more orders like this one. We asked customers what was their experience and all of them say that they didn't used reordering, they paid for the single order and multiple orders was created.

You probably need more information like logs or FTP login. Let me know about it.

Buckaroo Payments (v 4.1.0)
PrestaShop version: 8.1.1
PHP version: 8.1.13

**Comment by Buckaroo-Rene** [comment]
Hi @gadnis,

Thank you, we'll take a look at the issue you're facing. Perhaps we need more information indeed.
We'll let you know when that is the case.

**Comment by gadnis** [comment]
Hi, @vegimcarkaxhija 
This order is successfull - transaction key: AC36ACFDEF0944399843CE8540F1A8A3
But we have 7 multiple canceld orders of the same person, see the [pic](https://prnt.sc/DrE-oHfsvkY5)

**Comment by Buckaroo-Rens** [comment]
@gadnis So this is not an bug, more an feature request. This specific person just did 7 pament attempts and for multiple reason he got rejected or the payment failed. In our currect plugin logic, every new attempt means an new order number. I totally get why especially in these situations things are getting an bit messy in the Presta admin portal with the amount of (failed) orders. But you have to understand that there are several payment methods that oblige us to use an different order/invoice number for every payment attempt. That's why we have this logic like this right now. 

So again, it's not an bug, but just current logic how we proces failed/canceled orders.

**Comment by gadnis** [comment]
@Buckaroo-Rens I just tried my self to place an order and found probably one of the reason why order is placed at least twice everytime. See [pic](https://prnt.sc/hls6dgSfF2qQ). You can see that I choice iDEAL payment, but I didn't choice the bank and I'm allowed to press button "Place order". So when I press I get [error](https://prnt.sc/akGUK56taQFQ) and the new order. I believe customer than goes back in the browser and places the order again untill he understand that he need to choose the bank 😁 Do you think this can be fixed?

**Comment by Buckaroo-Rens** [comment]
Thats a good find @gadnis and might indeed be the reason for a lot of 'spam'. @Buckaroo-Rene can we have a look at this?

**Comment by Buckaroo-Rene** [comment]
@gadnis Thank you for your explanation. We'll look into a solution for it.

**Comment by Buckaroo-Rene** [comment]
Hi @gadnis,

This issue has been resolved in our latest release: [v4.2.0](https://github.com/buckaroo-it/PrestaShop/releases/tag/4.2.0)
Thanks again for informing us about this issue.

**Comment by gadnis** [comment]
Hi @Buckaroo-Rene 

Our customers still can press "Place order" button without selecting a bank. 

See [picture](https://prnt.sc/ZbERpSXEPTmv)
Shop: [adea](https://www.adeachocolate.com)

We use [Warehouse](https://themeforest.net/item/warehouse-responsive-prestashop-16-theme-blog/3178575) theme if this is relevent to the theme.

Maybe you could point me to a merged pull-request which solved the problem?

**Comment by Buckaroo-Rene** [comment]
Hi @gadnis ,

Thank you for your message.
We already created an additional fix that will be included in a v4.2.1 release.
Currently working on that so I will let you know when that fix is live and this issue is completely resolved.

**Comment by gadnis** [comment]
Hi, @Buckaroo-Rens 

Regarding this explanation:
> @gadnis So this is not an bug, more an feature request. This specific person just did 7 pament attempts and for multiple reason he got rejected or the payment failed. In our currect plugin logic, every new attempt means an new order number. I totally get why especially in these situations things are getting an bit messy in the Presta admin portal with the amount of (failed) orders. But you have to understand that there are several payment methods that oblige us to use an different order/invoice number for every payment attempt. That's why we have this logic like this right now.
> 
> So again, it's not an bug, but just current logic how we proces failed/canceled orders.

I have a video where the customer failed to pay on the first attempt. It appears that he was redirected back to our page instead of encountering the error message within the Buckaroo payment gateway. This would have allowed the customer to use a different card or correct any errors within the Buckaroo interface.

Is this the expected behavior, or could something be done to at least redirect the customer to a "re-order" page instead of the homepage?

While I appreciate this particular customer's patience, other customers might become frustrated and leave the shop prematurely. 

Transaction keys:
9EC88FD586234CCE874A1DC740383E4A
F9CBA197CB6D41F797517884910477F5
[video](https://www.dropbox.com/scl/fi/c2qzk1ta68sgajt6gsd7s/adeachocolate-MYWUDPMEV.mov?rlkey=q4toh4huptsm4yf1s9lyef6le&dl=0)

**Comment by Buckaroo-Rene** [comment]
Hi @gadnis ,

Thank you for sharing this experience/information.
Ideally you would like to redirect the consumer back to the payment selection instead of a homepage with a error message for example.
I'll check with the team whether this is possible while also following PrestaShop's default payment process.

Will let you know what comes out of that research.
Our reference for it is this ticket number: BP-4042

Best Regards,
René
