### ISSUE TITLE
BP-3473 Status changed from "in backorder not payed" to "payed"

### ISSUE THREAD

**Issue by Frankyet** [buckaroo-it/PrestaShop#141]
If a order is being payed and there are artcles not in stock it start with status "inbackorder not payed" but after order is sucsesfull payed it changed to status "payed" and that is not correctly is should be status "in backorder payed"
![image](https://github.com/buckaroo-it/PrestaShop/assets/22242384/b5def696-5688-4939-879a-395edaa1d2d3)
This will give you a wrong image of the order.

It should look like this...
![image](https://github.com/buckaroo-it/PrestaShop/assets/22242384/69841971-ec49-4ad4-b30b-8765350dc387)

**Comment by Buckaroo-Rene** [comment]
@Frankyet ,

Thanks again for pointing out an issue. We highly appreciate your feedback.
I was able to reproduce this issue and we'll look for an solution for it.

Best Regards,
René

**Comment by Buckaroo-Rene** [comment]
@Frankyet ,
For your information:
This has been resolved in the new release: [v4.2.0](https://github.com/buckaroo-it/PrestaShop/releases/tag/4.2.0)

Thanks for informing us about the issue.
