### ISSUE TITLE
BP-3472 Not able to use decimals for the payment fee settings

### ISSUE THREAD

**Issue by Frankyet** [buckaroo-it/PrestaShop#143]
If enetering a decimal in the settingspage in field paymentfee it will remove the ". " so no deceimals are possible.

it will remove "," aswell "." it shouel not remove but change the "," into "." an leave the "."

![image](https://github.com/buckaroo-it/PrestaShop/assets/22242384/136c30ab-d827-45b1-a67c-c4cbc06c57b9)
7.95 will changed into 795 at the moment.
I had to go to the database and changed it by hand.

**Comment by Buckaroo-Rene** [comment]
@Frankyet,

Thank you for mentioning this issue. We'll look into this issue and try to create a fix for it.
Good that you found a workaround by changing it in the database.

Best Regards,
René

**Comment by Buckaroo-Rene** [comment]
@Frankyet ,
For your information:
This has been resolved in the new release: [v4.2.0](https://github.com/buckaroo-it/PrestaShop/releases/tag/4.2.0)

Thanks for informing us about the issue.
