### ISSUE TITLE
BP-3478 Billink payment methode will result in error 500

### ISSUE THREAD

**Issue by Frankyet** [buckaroo-it/PrestaShop#145]
Whem payment methode Billink is sellected and fill in the fields and select order/pay, it will give error 500 after waiting a few seconds and it will jam the system.

in the backoffice there is an order created with status waiting for payment. in https://plaza.buckaroo.nl/ there is noting received.

**Comment by Buckaroo-Rene** [comment]
Hi @Frankyet ,

Thank you for your message. Can you perhaps share a random transaction key from a succesfull transaction?
Then I can double check your Buckaroo account to see if it is not a subscription issue or something like that.
Because we don't see this problem happening on our own staging environment.

Do you have some sort of logs or perhaps can you share the staging environment with us so we can check this on your staging.

Best Regards,
René

**Comment by Frankyet** [comment]
Hello René,

Where can I found the random transaction key?
Buckaroo made for me a Billink subscription, in the test fase i did get indead a error that i had no subscription for billink.
I soon i swich on debug it will hang on after hit the order/pay button, so no errors will showing.

I will creat a user login for the back-office an post it.

best regard,
Frank

**Comment by Frankyet** [comment]
Hello René,

Can you give me a e-mail adres to where I can send the login for mine Prestshop backoffice?

Best regards,
Frank

**Comment by Buckaroo-Rene** [comment]
Hi @Frankyet,
You can send us an transaction key from any transaction in the Buckaroo plaza.
When you are logged in at the Buckaroo Plaza, you can go to transactions and click on a random transaction in the transaction overview. Once you've clicked on the transaction a new screen will open with all the transaction information, including an transaction key.

You can also provide us the test website URL and name of the company.
This can be send by e-mail to: support@buckaroo.nl

Then we'll pick it up from there together with our support team.

Best Regards,
René

**Comment by Frankyet** [comment]
Hello René,

Oke the next transaction key is from the payment after the error Billink.
1E184D6E01684E78ADB90D204055C683

The Billink order did not creat anny in Buckaroo plaza.

Best regards,
Franjk

**Comment by Buckaroo-Rene** [comment]
Hi @Frankyet ,

Thanks, my colleagues from tech support are looking into it right now.
We'll pick it up by e-mail.

Best Regards,
René

**Comment by Frankyet** [comment]
additional information:
As soon you do not use a payment fee for Billing it will work in test or live setting.

Best regards,
Frank

**Comment by Buckaroo-Rene** [comment]
@Frankyet ,
Thanks, we are working on this issue right now.

**Comment by Buckaroo-Rene** [comment]
@Frankyet ,
For your information:
This has been resolved in the new release: [v4.2.0](https://github.com/buckaroo-it/PrestaShop/releases/tag/4.2.0)

Thanks for informing us about the issue.
