### ISSUE TITLE
BP-3482 Payment fee not visible in some places (order confirmation page - Backoffice area)

### ISSUE THREAD

**Issue by Frankyet** [buckaroo-it/PrestaShop#151]
After payment with the use of payment fee there is no showing of the payment fee in the order-conformation page.
It is showing correctly on the invoice pdf.
Also there is noting vissable about payment fee in the order-page in the back-office.

![image](https://github.com/buckaroo-it/PrestaShop/assets/22242384/ad6ac683-c7cd-4636-8374-911a3cf1921e)

best regards,
Frankyet

**Comment by Buckaroo-Rene** [comment]
Hi @Frankyet ,

Thank you for your message. We'll look into this issue.

**Comment by Frankyet** [comment]
Hello Rene,

Probely it is using a hook on the conformation page and the Buckaroo API did not hook it perhaps it is already hooked or override by a other API.

best regards,
Frankyet

**Comment by Frankyet** [comment]
Also the e-mails that are send to customer after placeing the order are not showing anny payment fee, and the total payed is also without the fee.

![image](https://github.com/buckaroo-it/PrestaShop/assets/22242384/f4941ade-0675-48b2-bf83-dcce2657d1d3)

best regards,
Frank

**Comment by Buckaroo-Rene** [comment]
Hi @Frankyet, 

We've made some adjustments in our latest release: [v4.3.0](https://github.com/buckaroo-it/PrestaShop/releases/tag/v4.3.0)

Best Regards,
René
