### ISSUE TITLE
BP-3482 There is no tax calculated on payment-fee

### ISSUE THREAD

**Issue by Frankyet** [buckaroo-it/PrestaShop#154]
There is no possibility to set a tax for payment-fee, if it is possible to select the shop-country tax than if a customer form a other country in the EU it will be using the local tax.
Also if the order is a intra-Community supply it will be 0% tax
and all this should be visible on the invoice, for example like this.

![image](https://github.com/buckaroo-it/PrestaShop/assets/22242384/f4814f21-3ac9-49fa-81ab-753bc44ae6ec)
This is what mine Paypal with a fee module creat.

Specially for companies is tax visibility important on the invoice.

**Comment by Buckaroo-Rene** [comment]
Hi @Frankyet ,

We've made some adjustments regarding this issue together with: [https://github.com/buckaroo-it/PrestaShop/issues/151](https://github.com/buckaroo-it/PrestaShop/issues/151)
These are available in our latest plugin version.
