### ISSUE TITLE
BP-3509 Status changed from "in backorder not payed" to "payed" (Issue #141)

### ISSUE THREAD

**Issue by Frankyet** [buckaroo-it/PrestaShop#155]
This issue should be solved in the last version but it is not always working coorrectly,
Today I had one order that was correctly and one not.....

![image](https://github.com/buckaroo-it/PrestaShop/assets/22242384/d19e2808-a859-446f-9145-c4c0978a6d18)

Best regards,
Frank

**Comment by Buckaroo-Rene** [comment]
Hi @Frankyet ,
Thanks, I noticed the order with the times in your images.
We'll take a look at it and let you know when it is fixed.

**Comment by Buckaroo-Rene** [comment]
Hi @Frankyet ,

We've made some adjustments in our latest release: [v4.3.0](https://github.com/buckaroo-it/PrestaShop/releases/tag/v4.3.0)
Thanks again for informing us about this issue.

Best Regards,
René
