### ISSUE TITLE
BP-3506 API stopped working error 2006

### ISSUE THREAD

**Issue by Frankyet** [buckaroo-it/PrestaShop#156]
on 23-03-25 payment via Buckaroo module gave the next error.
![image](https://github.com/buckaroo-it/PrestaShop/assets/22242384/a474365f-d6a0-40f5-b499-3c75c575bb52)

order is created.
![image](https://github.com/buckaroo-it/PrestaShop/assets/22242384/89311bd5-a8ff-4162-b0e7-99747d546495)

switched over to other Payment provider and that did work.

**Comment by Buckaroo-Rene** [comment]
@Frankyet ,
Probably we'll need some more information for this error, since the latest transaction date in your Buckaroo account is from the 22th. We don't see this attempt from the 23rd.
We will investigate and let you know when more information is needed by our developers.

**Comment by Frankyet** [comment]
I have made just a test order with ideal on running shop and still error.

![image](https://github.com/buckaroo-it/PrestaShop/assets/22242384/d5631d24-06fb-44de-8282-de9424dba5ff)

Did it also on the test webshop and the same error.

you can tested on the test shop.

best regards,
Frank

**Comment by Buckaroo-Rene** [comment]
@Frankyet We've looked at your test website with www......nl//prestashop8/
But we are already getting an error 500 when adding any product in the cart.
Do you have specific products to test with or is there another issue going on right now?

![image](https://github.com/buckaroo-it/PrestaShop/assets/105488705/a7653068-fd7b-4b53-aebd-2bf6bb420daf)

**Comment by Frankyet** [comment]
Oke that is weared, I have set debug on and now you can add products, i have done it yet, and tried to pay with ideal and did geat this error.
![image](https://github.com/buckaroo-it/PrestaShop/assets/22242384/0f7bb12a-417e-4632-8be3-65c4eee9b050)

best regards,
Frank

**Comment by Buckaroo-Rene** [comment]
@Frankyet ,

My colleague Sander from our technical support team will contact you by e-mail regarding this issue since we'll need some more access to do some proper research unfortunately.
