### ISSUE TITLE
Empty module configuration page because of 404 error

### ISSUE THREAD

**Issue by gadnis** [buckaroo-it/PrestaShop#96]
Hi,

module configuration page is not showing any configuration tabs (Settings, Payments methods,...) the response is 404 for a resource. 

For example page settings url: domain.example.com/index.php?fc=module&module=buckaroo3&controller=settings
returns response 404 - page not found.
[screenshot  here](https://prnt.sc/o0tzhDdESEuB)

This happen few times and neer the midnight.

Prestashop ver. 8.1.1
Module ver. 4.0.1
PHP version: 8.1.13

**Comment by Buckaroo-Rens** [comment]
@gadnis Thank you for reporting your problem. We will look into this as soon as possible.

**Comment by Buckaroo-Rene** [comment]
@gadnis We've discussed it within the team.
Did you try to clear the cache? If that is not working I think we'll need to have some more information like logs or check it on your staging if possible (temporary SSH).
If the problem persists after clearing the cache, then pleas contact our technical support team by e-mail, see their contact details below. We'll then pick it up from there.

E-mail: [Support@buckaroo.nl](mailto:support@buckaroo.nl)

**Comment by gadnis** [comment]
@Buckaroo-Rene hi, a tried clearing cache but ended up by uninstalling module completelly and reinstall, now all working as before. If the problem will come up I will let you know about that. Thanks.

**Comment by Buckaroo-Rene** [comment]
@gadnis ,
Thank you for your reply. Good to hear that the problem is resolved for now.
Something that came up on my mind is the following:
Did you do a update form a older version when you've installed the plugin the first time?
Because maybe this issue was caused by upgrading for like a v3.x plugin version.

**Comment by gadnis** [comment]
@Buckaroo-Rene ,
I used [this url](https://github.com/buckaroo-it/PrestaShop/releases/download/4.0.1/buckaroo3.zip) to download the latest version. So this file was the first and only one in the server.

**Comment by Buckaroo-Rene** [comment]
@gadnis,
Thanks for the additional information.
Please let us know when this happens again.
We'll try to reproduce this in some more ways.
